version: "3"

services:
  share-helper:
    container_name: share-helper
    build: .
    ports:
      - "8083:8083/tcp"
    environment:
      TZ: 'Europe/Berlin'
      SHARE_HELPER_PORT: 8083
    restart: unless-stopped


