version: "3"

services:
  blog:
    container_name: share-helper
    image: b0wter/share-helper:latest
    ports:
      - "8083:8083/tcp"
    environment:
      TZ: 'Europe/Berlin'
      SHARE_HELPER_PORT: 8083
    restart: unless-stopped


